'use strict';
const CARDS=[
{title:'من هو عثمان بن عفان؟',label:'هويته ومكانته',icon:'✦',color:'#26765e',bg:'#e2f2e7',points:['قرشي من بني أمية، ولد في مكة.','ثالث الخلفاء الراشدين.','من العشرة المبشرين بالجنة.'],value:'مكانة عظيمة في تاريخ الإسلام',q:'ما ترتيبه بين الخلفاء الراشدين؟',a:'هو ثالث الخلفاء الراشدين.'},
{title:'لماذا لقب بذي النورين؟',label:'لقبه وأسرته',icon:'✧',color:'#866336',bg:'#fff0d0',points:['تزوج رقية بنت رسول الله صلى الله عليه وسلم.','بعد وفاتها تزوج أختها أم كلثوم.','لذلك اشتهر بلقب «ذو النورين».'],value:'صلة كريمة ببيت النبوة',q:'من الزوجتان اللتان ارتبط بهما لقب ذو النورين؟',a:'رقية وأم كلثوم، ابنتا رسول الله صلى الله عليه وسلم.'},
{title:'من السابقين إلى الإسلام',label:'إسلامه وهجرته',icon:'⌂',color:'#426da0',bg:'#e7f1fd',points:['أسلم على يد أبي بكر الصديق رضي الله عنه.','هاجر مع رقية إلى الحبشة.','ثم هاجر إلى المدينة المنورة.'],value:'الثبات على الإيمان',q:'إلى أين هاجر قبل المدينة؟',a:'هاجر إلى الحبشة مع زوجته رقية.'},
{title:'حياء وعلم وكرم',label:'أخلاقه وعلمه',icon:'♡',color:'#906387',bg:'#f5e8f2',points:['اشتهر بشدة الحياء وحسن الخلق.','كان تاجرا كريما جوادا.','كان حافظا للقرآن، وروى أحاديث عن النبي.'],value:'الحياء خلق جميل',q:'ما الخلق الذي اشتهر به عثمان؟',a:'اشتهر بالحياء، وكان كريما جوادا.'},
{title:'عطاء يصل إلى الجميع',label:'عطاؤه للمسلمين',icon:'◉',color:'#ad6937',bg:'#fff0df',points:['اشترى بئر رومة لينتفع المسلمون بمائها.','أنفق من ماله على تجهيز جيش العسرة.','ساهم في توسعة المسجد النبوي.'],value:'أعطي لينتفع غيري',q:'كيف خدم المسلمين بماله؟',a:'اشترى بئر رومة، وجهز جيش العسرة، وساهم في توسعة المسجد النبوي.'},
{title:'خدمة القرآن الكريم',label:'المصاحف',icon:'▤',color:'#7063a3',bg:'#eeeafa',points:['بدأ جمع القرآن في عهد أبي بكر الصديق.','في عهد عثمان نسخت المصاحف.','جمع الناس على مصحف واحد.'],value:'العناية بكتاب الله',q:'هل بدأ جمع القرآن في عهد عثمان؟',a:'بدأ جمعه في عهد أبي بكر. وفي عهد عثمان نسخت المصاحف وجمع الناس على مصحف واحد.'},
{title:'إنجازات في عهده',label:'الدولة والأسطول',icon:'⚓',color:'#287c88',bg:'#e1f2f4',points:['اتسعت الدولة الإسلامية في عهده.','أنشئ أول أسطول إسلامي.','انتصر المسلمون في معركة ذات الصواري.'],value:'التطوير والعمل النافع',q:'ما اسم المعركة البحرية في عهده؟',a:'معركة ذات الصواري.'},
{title:'مواقف ومحطات أخيرة',label:'مواقف وتواريخ',icon:'◷',color:'#597549',bg:'#eef3dd',points:['أرسله النبي إلى قريش للتفاوض في الحديبية.','تولى الخلافة سنة ٢٤ هـ.','امتنع عن القتال حقنا للدماء، واستشهد سنة ٣٥ هـ.'],value:'الحرص على حقن الدماء',q:'لماذا امتنع عن قتال من حاصروا بيته؟',a:'امتنع عن القتال حقنا للدماء.'}
];
const CHOICES=[{q:'ما ترتيب عثمان بين الخلفاء الراشدين؟',options:['الأول','الثالث','الرابع'],a:'الثالث',note:'عثمان هو ثالث الخلفاء الراشدين.'},{q:'على يد من أسلم عثمان؟',options:['أبي بكر الصديق','عمر بن الخطاب','خالد بن الوليد'],a:'أبي بكر الصديق',note:'أسلم على يد أبي بكر الصديق رضي الله عنه.'},{q:'إلى أين هاجر مع رقية قبل المدينة؟',options:['الشام','مصر','الحبشة'],a:'الحبشة',note:'هاجر إلى الحبشة، ثم إلى المدينة.'},{q:'ما اسم المعركة البحرية في عهده؟',options:['بدر','ذات الصواري','أحد'],a:'ذات الصواري',note:'انتصر المسلمون في معركة ذات الصواري.'}];
const TRUTH=[{q:'لقب عثمان بذي النورين لأنه تزوج ابنتي النبي.',a:'صح',note:'تزوج رقية، ثم أم كلثوم بعد وفاة رقية.'},{q:'اشتهر عثمان بالبخل وعدم مساعدة الناس.',a:'خطأ',note:'اشتهر بالكرم والجود والحياء.'},{q:'بدأ جمع القرآن في عهد أبي بكر الصديق.',a:'صح',note:'ثم نسخت المصاحف في عهد عثمان.'},{q:'تولى عثمان الخلافة سنة ٣٥ هـ.',a:'خطأ',note:'تولى الخلافة سنة ٢٤ هـ، واستشهد سنة ٣٥ هـ.'}];
const PAIRS=[{id:'well',work:'شراء بئر رومة',result:'توفير الماء للمسلمين'},{id:'army',work:'تجهيز جيش العسرة',result:'دعم الجيش من ماله'},{id:'quran',work:'نسخ المصاحف',result:'جمع الناس على مصحف واحد'},{id:'navy',work:'إنشاء الأسطول',result:'تطوير القوة البحرية'}];
const $=id=>document.getElementById(id);let cardIndex=0,flipped=false,selected=null;const solved=new Set(),attempts=new Map();let firstStars=0;
const ar=n=>String(n).replace(/\d/g,x=>'٠١٢٣٤٥٦٧٨٩'[x]);
function renderCard(){const card=CARDS[cardIndex];flipped=false;$('flashcard').style.setProperty('--accent',card.color);$('flashcard').style.setProperty('--bg',card.bg);$('card-icon').textContent=card.icon;$('card-kicker').textContent='بطاقة المعرفة • '+card.label;$('card-number').textContent=ar(cardIndex+1).padStart(2,'٠');$('card-title').textContent=card.title;$('card-points').replaceChildren(...card.points.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('card-value').textContent=card.value;$('recall-question').textContent=card.q;$('recall-answer').textContent=card.a;$('recall-answer').hidden=true;$('reveal').hidden=false;$('card-front').hidden=false;$('card-back').hidden=true;$('flip').textContent='اقلب البطاقة • اختبر ذاكرتك ↻';$('flip').setAttribute('aria-pressed','false');$('card-counter').textContent=ar(cardIndex+1)+' / ٨';$('prev').disabled=cardIndex===0;$('next-card').textContent=cardIndex===7?'لنبدأ التمارين ↓':'المحطة التالية ←';[...$('steps').children].forEach((el,i)=>el.setAttribute('aria-current',String(i===cardIndex)));[...$('dots').children].forEach((el,i)=>el.classList.toggle('on',i===cardIndex))}
CARDS.forEach((card,i)=>{const b=document.createElement('button');b.className='step';b.type='button';b.innerHTML='<span>'+ar(i+1)+'</span>';b.append(document.createTextNode(card.label));b.addEventListener('click',()=>{cardIndex=i;renderCard()});$('steps').append(b);$('dots').append(document.createElement('i'))});renderCard();
$('next-card').addEventListener('click',()=>{if(cardIndex===7){$('practice').scrollIntoView({behavior:'smooth'});$('tab-choice').focus({preventScroll:true});return}cardIndex++;renderCard();$('card-title').focus({preventScroll:true})});$('prev').addEventListener('click',()=>{if(cardIndex>0){cardIndex--;renderCard();$('card-title').focus({preventScroll:true})}});$('flip').addEventListener('click',()=>{flipped=!flipped;$('card-front').hidden=flipped;$('card-back').hidden=!flipped;$('flip').textContent=flipped?'العودة إلى المعلومات ↻':'اقلب البطاقة • اختبر ذاكرتك ↻';$('flip').setAttribute('aria-pressed',String(flipped))});$('reveal').addEventListener('click',()=>{$('recall-answer').hidden=false;$('reveal').hidden=true});
function openTab(type,focus=false){for(const t of ['choice','truth','match']){$('tab-'+t).setAttribute('aria-selected',String(t===type));$('panel-'+t).hidden=t!==type}if(focus)$('tab-'+type).focus({preventScroll:true})}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{openTab(b.dataset.open,true);$('practice').scrollIntoView({behavior:'smooth'})}));
document.querySelectorAll('[role=tab]').forEach((b,i)=>b.addEventListener('keydown',e=>{let j;if(e.key==='ArrowLeft')j=(i+1)%3;else if(e.key==='ArrowRight')j=(i+2)%3;else if(e.key==='Home')j=0;else if(e.key==='End')j=2;else return;e.preventDefault();openTab(['choice','truth','match'][j],true)}));
function updateProgress(){const count=solved.size;$('exercise-count').textContent=ar(count)+' / ١٢';$('exercise-progress').setAttribute('aria-valuenow',count);$('exercise-fill').style.width=count/12*100+'%';for(const type of ['choice','truth','match']){$('tab-'+type).querySelector('span').textContent=ar([...solved].filter(k=>k.startsWith(type)).length)+' / ٤'}}
function markSolved(key){if(solved.has(key))return;solved.add(key);if(attempts.get(key)===1)firstStars++;updateProgress();if(solved.size===12)finish()}
function makeQuiz(type,questions){const list=$(type+'-list');list.replaceChildren();questions.forEach((q,i)=>{const key=type+i,box=document.createElement('article');box.className='quiz';const h=document.createElement('h4');h.textContent=ar(i+1)+' · '+q.q;const answers=document.createElement('div');answers.className='answers';const feedback=document.createElement('p');feedback.className='quiz-feedback';feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');feedback.textContent='اختر إجابتك.';for(const option of q.options||['صح','خطأ']){const b=document.createElement('button');b.className='answer';b.textContent=option;b.type='button';b.addEventListener('click',()=>{if(solved.has(key)||b.disabled)return;attempts.set(key,(attempts.get(key)||0)+1);if(option===q.a){b.classList.add('correct');box.classList.add('done');answers.querySelectorAll('button').forEach(x=>x.disabled=true);feedback.textContent=(attempts.get(key)===1?'⭐ صحيح من أول مرة! ':'✓ أحسنت! ')+q.note;markSolved(key)}else{b.classList.add('wrong');b.disabled=true;feedback.textContent='حاول مرة أخرى. '+(type==='truth'?q.note:'اقرأ السؤال بهدوء.')}});answers.append(b)}box.append(h,answers,feedback);list.append(box)})}
function selectCard(id){if(solved.has('match'+id))return;selected=id;document.querySelectorAll('.drag-card').forEach(b=>{b.classList.toggle('selected',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id))});$('drag-status').textContent='اختر مكان: '+PAIRS.find(p=>p.id===id).work}
function dropCard(targetId,sourceId=selected){if(!sourceId){$('drag-status').textContent='اختر بطاقة من بطاقات الأعمال أولا.';return}const key='match'+sourceId;if(solved.has(key))return;attempts.set(key,(attempts.get(key)||0)+1);if(sourceId!==targetId){$('drag-status').textContent='ليست النتيجة المناسبة. حاول مرة أخرى مع البطاقة نفسها.';return}const pair=PAIRS.find(p=>p.id===sourceId);const source=document.querySelector('.drag-card[data-id="'+sourceId+'"]');source.disabled=true;source.draggable=false;source.classList.remove('selected');source.setAttribute('aria-pressed','false');const target=document.querySelector('.drop[data-id="'+targetId+'"]');target.classList.add('matched');target.querySelector('small').textContent='✓ '+pair.work;target.disabled=true;selected=null;$('drag-status').textContent=(attempts.get(key)===1?'⭐ توصيل صحيح من أول مرة! ':'✓ توصيل صحيح! ')+pair.work+' ← '+pair.result;markSolved(key)}
function makeMatch(){$('drag-bank').replaceChildren();$('drop-bank').replaceChildren();for(const pair of PAIRS){const source=document.createElement('button');source.type='button';source.className='drag-card';source.draggable=true;source.dataset.id=pair.id;source.textContent='⋮⋮ '+pair.work;source.setAttribute('aria-label','بطاقة '+pair.work);source.setAttribute('aria-pressed','false');source.addEventListener('click',()=>selectCard(pair.id));source.addEventListener('dragstart',e=>{selectCard(pair.id);e.dataTransfer.setData('text/plain',pair.id);e.dataTransfer.effectAllowed='move'});$('drag-bank').append(source)}for(const i of [2,0,3,1]){const pair=PAIRS[i],target=document.createElement('button');target.type='button';target.className='drop';target.dataset.id=pair.id;target.setAttribute('aria-label','مكان '+pair.result);target.textContent=pair.result;const hint=document.createElement('small');hint.textContent='أسقط البطاقة هنا أو اضغط';target.append(hint);target.addEventListener('click',()=>dropCard(pair.id));target.addEventListener('dragover',e=>{e.preventDefault();if(!target.disabled){target.classList.add('over');e.dataTransfer.dropEffect='move'}});target.addEventListener('dragleave',()=>target.classList.remove('over'));target.addEventListener('drop',e=>{e.preventDefault();target.classList.remove('over');if(!target.disabled)dropCard(pair.id,e.dataTransfer.getData('text/plain'))});$('drop-bank').append(target)}}
function finish(){$('completion').hidden=false;$('result-heading').textContent=firstStars>=10?'أنت نجم المعرفة!':'أحسنت… أكملت رحلة التعلم!';$('result-message').textContent='تعلمت، وحاولت، وأكملت التحديات الاثني عشر. الآن استعد لمغامرة صيد الكلمات.';$('result-stars').textContent=ar(firstStars)+' / ١٢'}
$('show-result').addEventListener('click',()=>{if(solved.size<12){$('drag-status').textContent='بقي '+ar(12-solved.size)+' تحديات. أكمل الجولات الثلاث لتكشف إنجازك.';return}finish();$('completion').scrollIntoView({behavior:'smooth'});$('result-heading').focus({preventScroll:true})});
function reset(){solved.clear();attempts.clear();firstStars=0;selected=null;$('completion').hidden=true;$('drag-status').textContent='اختر بطاقة لتبدأ.';makeQuiz('choice',CHOICES);makeQuiz('truth',TRUTH);makeMatch();updateProgress();openTab('choice')}
$('reset-exercises').addEventListener('click',()=>{reset();$('practice').scrollIntoView({behavior:'smooth'});$('tab-choice').focus({preventScroll:true})});reset();
